version: '3'

services:
  portfolio:
    ports:
      - "80:80"
      - "443:443"
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - /etc/ssl/my-server:/etc/nginx/certs
