version: '3'
services:
  portfolio:
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/alexjcm/Documentos/projects/portfolio-frontend:/portfolio-frontend
    working_dir: /portfolio-frontend