name: Publish docker image (CI)

on:
  push:
    branches: ["main"]

jobs:
  push_to_registry:
    name: Push docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

        # Setting up Docker Buildx with docker-container driver is required
        # at the moment to be able to use a subdirectory with Git context
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #   # Docker images to use as base name for tags
      #     images: ${{ secrets.DOCKER_HUB_USERNAME }}/porfolio
      #   # generate Docker tags based on the following events/attributes
      #     tags: |
      #       type=schedule
      #       type=ref,event=branch
      #       type=ref,event=pr
      #       type=semver,pattern={{version}}
      #       type=semver,pattern={{major}}.{{minor}}
      #       type=semver,pattern={{major}}
      #       type=sha

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          # context: "{{defaultContext}}:mysubdir"
          context: .
          file: docker/DockerfileProLite
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio:latest
          #tags: ${{ steps.meta.outputs.tags }}
          #labels: ${{ steps.meta.outputs.labels }}
